#!/bin/bash

# Call format
# ../pipair $SOURCE.bc $SUPPORT $CONFIDENCE > $TESTNAME_$SUPPORT_$CONFIDENCE.out 2>&1

# Generate callgraph and send it to raw format file
opt -f -print-callgraph $1 2> cg

# Remove first 5 lines (message we do not want)
sed -e '1,5d' < cg > cg.txt

make

# Run our debugger on it
Debugger cg.txt $2 $3

make clean
