#!/bin/bash

# Call format
# ../pipair $SOURCE.bc $SUPPORT $CONFIDENCE > $TESTNAME_$SUPPORT_$CONFIDENCE.out 2>&1

CURR_DIR=$(pwd)
ARG1=$CURR_DIR/$1

# Generate callgraph and send it to raw format file
opt -print-callgraph $ARG1 >tmp.txt 2>cg.txt
make -C ../ > tmp.txt

# Run our debugger on it
if [[ -z $2 && -z $3 ]]; then
	../Debugger cg.txt >&1
else
	../Debugger cg.txt $2 $3 >&1
fi
make clean -C ../ > tmp.txt
rm tmp.txt

